### ISSUE TITLE
CREANDO UN ARCHIVO EN EL REPOSITORIO LOCAL

### ISSUE THREAD

**Issue by SLyukukui** [SistemasTecTlaxiaco/cursogithubhilariovidal#2]
SE CREO EL REPOSITORIO LOCAL DE GITHUB
![image](https://user-images.githubusercontent.com/89793643/131377463-c73725f7-b214-4495-b9ab-b396ed7695ea.png)
TERMINADO...

**Comment by josealfredo79** [comment]
esta bien hecho y revisado
