### ISSUE TITLE
crear mi primera tarea en GitHub Classroom 

### ISSUE THREAD

**Issue by SLyukukui** [SistemasTecTlaxiaco/cursogithubhilariovidal#7]
3.2 aprendiendo cómo crear mi primera tarea en GitHub Classroom:
![image](https://user-images.githubusercontent.com/89793643/131700416-b41de259-25ef-4448-961d-ebfade7f3d60.png)

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
