### ISSUE TITLE
tarea 3.2.1

### ISSUE THREAD

**Issue by SLyukukui** [SistemasTecTlaxiaco/cursogithubhilariovidal#9]
![image](https://user-images.githubusercontent.com/89793643/131705281-0178409b-4aee-4f5f-895b-a6f9ed32f958.png)
![image](https://user-images.githubusercontent.com/89793643/131705308-c2737968-49cf-4ae4-b732-c65dc6476c81.png)
![image](https://user-images.githubusercontent.com/89793643/131705332-17cd7b2b-696c-46e7-806f-4571736df238.png)

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
